name: Github Act 02
on:
  push:
     branches: ["main"]
  
jobs:
  build:
    runs-on: ubantu-latest
    steps:
      -name: Checkout
       uses: action/Checkout@v3
      -name: Setup Node
       uses: action/setup-node@v3
       with:
        node-version: "16"
      -name: Install Dependencies
       run: npm ci
      -name: Build Project
       run: npm run build
  deploy:
    runs-on: ubantu-latest
    need: build
    environment:
      name: github-pages
      url: ${{ steps.deplyomemnt.outputs.psge_url }}
    steps:
    name: Deploye to github pages
    id: deplyoment
    uses: action/setup-node@v3
